# The URL the site will be built for
base_url = "https://peopleforbikes.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "juice"
title = "PeopleForBikes Tech"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "inspired-github"

[extra]
# Put all your custom variables here
juice_logo_name = "PeopleForBikes Tech"
juice_logo_path = "logo_pfb.svg"
juice_extra_menu = [
    # { title = "Overview", link = "/" },
    # { title = "Community", link = "/community" },
    { title = "Docs ⍈", link = "https://peopleforbikes.github.io/docs" },
    { title = "Github ⍈", link = "https://github.com/PeopleForBikes" }
]
site_description = "PeopleForBikes community site."
repository_url = "https://github.com/PeopleForBikes/PeopleForBikes.github.io"
